# @package _global_
defaults:
  - /generate_common
  - _self_

checkpoint: kuleshov-group/caduceus-ph_seqlen-131k_d_model-256_n_layer-16
revision: b0477522ac5d044ad03578aa724ec8e4bdbd405b

# Index into outputs.hidden_states; -1 is the last hidden state.
layer_index: -1

# Effective batch is min(batch_size, gen_chunk_size), so raise both together.
batch_size: 1024

update_config: false
train_output_path: data/hg38/train_caduceus_${seq_length}_hg38_per_token.h5
val_output_path: data/hg38/val_caduceus_${seq_length}_hg38_per_token.h5
test_output_path: data/hg38/test_caduceus_${seq_length}_hg38_per_token.h5
